version: '3.3' 
  
volumes: 
  pg_data: 
  static: 
  media: 
  
services: 
  # db: 
  #   env_file: .env 
  #   image: postgres:13 
  #   volumes: 
  #    - pg_data:/var/lib/postgresql/data/ 
  #   restart: always 
  
  backend: 
    env_file: .env 
    build: ./backend/ 
    volumes: 
     - static:/app/static/ 
     - media:/app/media/ 
    # depends_on: 
    #  - db 
    restart: always 
  
  frontend: 
    build: ./frontend/ 
    command: cp -r /app/build/. /app/static/ 
    volumes: 
     - static:/app/static/ 
  
  gateway: 
    build: ./nginx/ 
    ports: 
     - 80:80 
    volumes: 
     - static:/app/static/ 
     - media:/app/media/
     - ./docs/:/app/static/api/docs/

    depends_on: 
     - backend 
     - frontend 
    restart: always