version: '3.3' 
  
volumes: 
  pg_final: 
  static: 
  media: 
  
services: 
  db: 
    env_file: .env
    image: postgres:13.10
    volumes: 
     - pg_final:/var/lib/postgresql/data/ 
  
  backend: 
    image: ubilby/ya_p_final_backend
    env_file: .env 
    volumes: 
     - static:/app/static/ 
     - media:/app/media/ 
    depends_on: 
     - db 
  
  frontend: 
    image: ubilby/ya_p_final_frontend
    command: cp -r /app/build/. /app/static/ 
    volumes: 
     - static:/app/static/ 
  
  gateway: 
    image: ubilby/ya_p_final_gateway
    ports: 
     - 9000:80
    volumes: 
     - static:/app/static/ 
     - media:/app/media/
     - ./docs/:/app/static/api/docs/

    depends_on: 
     - backend 
     - frontend 
