# Generated by Django 3.2.3 on 2023-10-28 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='subscriptions',
        ),
    ]
