# Generated by Django 3.2.3 on 2023-10-28 08:46

import backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_account_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[backend.validators.username_validator]),
        ),
    ]
